"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import ProgramHeader,{ProgramFooter} from '../programs/program-header';
import {type Enrollment,enrollmentLabel} from '../lib/program-data';
import {demoApplications,readDemoApplications} from '../lib/demo-applications';
import '../programs/programs.css';
import './account.css';
const guidance:Record<Enrollment['status'],string>={submitted:'신청이 접수되었습니다. 제출한 내용을 바탕으로 참여 가능 여부를 확인합니다.',reviewing:'운영자가 신청서를 검토하고 있습니다. 결과가 확정되면 이곳에 반영됩니다.',accepted:'참가 가능한 상태입니다. 결제와 그룹별 일정은 별도 안내를 확인해 주세요.',declined:'이번 프로그램에는 함께하기 어렵게 되었습니다. 다음 모집 프로그램을 확인해 주세요.',cancelled:'취소된 신청입니다. 다른 프로그램에서 다시 만나요.'};
export default function AccountDashboard({preview=false}:{preview?:boolean}){
 const [items,setItems]=useState<Enrollment[]>([]),[user,setUser]=useState({name:'',email:''}),[loading,setLoading]=useState(!preview),[error,setError]=useState(''),[tab,setTab]=useState('applications'),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<string|null>(null),[member,setMember]=useState('sample-member-1');
 async function load(){setLoading(true);setError('');try{const[a,b]=await Promise.all([fetch('/api/auth/session'),fetch('/api/enrollments')]);if(a.status===401||b.status===401){location.replace('/login?returnTo=/account');return;}const u=await a.json() as {user:{name:string;email:string}|null},d=await b.json() as {enrollments:Enrollment[];error?:string};if(!a.ok||!b.ok||!u.user)throw Error(d.error||'정보를 불러오지 못했습니다.');setUser(u.user);setItems(d.enrollments);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{if(!preview){load();return;}const id=new URLSearchParams(location.search).get('member');if(id&&demoApplications.some(x=>x.user_id===id))setMember(id);},[preview]);
 useEffect(()=>{if(!preview)return;const sync=()=>{const x=readDemoApplications().filter(x=>x.user_id===member);setItems(x);setUser({name:x[0]?.name||'',email:x[0]?.email||''});};sync();window.addEventListener('storage',sync);window.addEventListener('focus',sync);window.addEventListener('offset-demo-change',sync);return()=>{window.removeEventListener('storage',sync);window.removeEventListener('focus',sync);window.removeEventListener('offset-demo-change',sync);};},[preview,member]);
 const visible=items.filter(x=>filter==='all'||x.status===filter),active=items.filter(x=>['submitted','reviewing'].includes(x.status)).length;
 return <div className="of-site"><ProgramHeader/><main className="of-member-wrap">
 {preview&&<div className="of-notice">가상 회원의 마이페이지입니다. <Link href="/admin/preview">어드민 미리보기 ↗</Link><label className="of-sample-select">샘플 회원 <select value={member} onChange={e=>{setMember(e.target.value);setSelected(null);}}>{demoApplications.map(x=><option key={x.user_id} value={x.user_id}>{x.name}</option>)}</select></label></div>}
 <div className="of-member-heading"><p>MY OFFSET</p><h1>마이페이지</h1><span>신청부터 참여까지, 나의 프로그램을 한곳에서 확인하세요.</span></div>
 <div className="of-member-layout"><aside className="of-member-nav"><div className="of-member-avatar" aria-hidden="true">{user.name.slice(0,1)||'O'}</div><h2>{user.name||'회원'}님</h2><p>{user.email}</p><nav aria-label="마이페이지 메뉴"><button aria-current={tab==='applications'?'page':undefined} onClick={()=>setTab('applications')}>신청 내역 <span>{items.length}</span></button><button aria-current={tab==='profile'?'page':undefined} onClick={()=>setTab('profile')}>회원 정보</button></nav>{!preview&&<form action="/api/auth/logout" method="post"><button className="of-member-logout">로그아웃</button></form>}</aside>
 <section className="of-member-content">{loading?<p role="status">회원 정보를 불러오는 중입니다.</p>:error?<div role="alert" className="of-notice">{error}<button onClick={load}>다시 시도</button></div>:tab==='profile'?<><h2>회원 정보</h2><p className="of-muted">Google 계정으로 로그인한 회원 정보입니다.</p><dl className="of-member-profile"><div><dt>이름</dt><dd>{user.name}</dd></div><div><dt>이메일</dt><dd>{user.email}</dd></div><div><dt>로그인 방식</dt><dd>Google</dd></div></dl><p className="of-muted">회원 정보와 관련해 도움이 필요하면 문의해 주세요.</p><a className="of-button secondary" href="mailto:offset.learn@gmail.com">회원 정보 문의</a></>:<>
 <div className="of-member-stats"><div><span>전체 신청</span><strong>{items.length}</strong></div><div><span>접수·검토 중</span><strong>{active}</strong></div><div><span>참가 가능</span><strong>{items.filter(x=>x.status==='accepted').length}</strong></div></div>
 <div className="of-member-section-heading"><h2>신청 내역</h2><Link href="/programs">프로그램 둘러보기 ↗</Link></div><div className="of-member-filters" role="group" aria-label="신청 상태 필터">{[['all','전체'],...Object.entries(enrollmentLabel)].map(([v,l])=><button key={v} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{l}</button>)}</div>
 {visible.length?visible.map(x=><article className="of-member-application" key={x.id}><div className="of-member-application-top"><span className={`of-member-status ${x.status}`}>{enrollmentLabel[x.status]}</span><time dateTime={x.created_at}>{new Date(x.created_at).toLocaleDateString('ko-KR')} 신청</time></div><h3>{x.title?.replaceAll('\n',' ')||'신청한 프로그램'}</h3><p>{guidance[x.status]}</p>{!["declined","cancelled"].includes(x.status)&&<div className="of-member-progress" aria-label={`현재 상태: ${enrollmentLabel[x.status]}`}>{['신청 접수','검토','참가 안내'].map((s,i)=><span key={s} className={i<=(x.status==='submitted'?0:x.status==='reviewing'?1:2)?'reached':''}>{s}</span>)}</div>}<button type="button" className="of-member-detail-toggle" aria-expanded={selected===x.id} onClick={()=>setSelected(selected===x.id?null:x.id)}>제출한 신청서 {selected===x.id?'접기 −':'보기 ＋'}</button>{selected===x.id&&<dl className="of-member-submission"><div><dt>신청 번호</dt><dd>{x.id}</dd></div><div><dt>신청자</dt><dd>{x.name} · {x.email}</dd></div><div><dt>신청 동기</dt><dd>{x.motivation}</dd></div><div><dt>포트폴리오</dt><dd>{/^https?:\/\//.test(x.portfolio)?<a href={x.portfolio} target="_blank" rel="noreferrer">제출한 포트폴리오 열기 ↗</a>:'등록된 링크를 확인해 주세요.'}</dd></div></dl>}<a className="of-member-inquiry" href={`mailto:offset.learn@gmail.com?subject=${encodeURIComponent('신청 문의 '+x.id)}`}>신청 관련 문의</a></article>):<div className="of-empty"><h3>{items.length?'선택한 상태의 신청이 없습니다.':'아직 신청한 프로그램이 없어요.'}</h3><p>새로운 배움의 기회를 찾아보세요.</p><Link className="of-button" href="/programs">프로그램 둘러보기</Link></div>}
 </>}</section></div></main><ProgramFooter/></div>;
}
